---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
- name: movie-fun

outputs:
- name: package-output

run:
  path: movie-fun/ci/tasks/package.sh

